---
- name: Launch EC2 instance using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    default_instance_prefix: "yaswanth-demo-instance"
    region: ap-south-1
    ami_id: ami-0a1235697f4afa8a4            # Amazon Linux 2023 AMI (ap-south-1)
    instance_type: t2.nano                   # 1vCPU 0.5 GiB Memory
    key_name: AL2023                         # Replace with your key pair name
    subnet_id: subnet-0b9b0f798dbe19be2      # Replace with your subnet ID
    security_group: sg-0703680985f56f283     # Replace with your security group ID


  tasks:
    - name: 🧮 Generate random suffix
      set_fact:
        suffix: "{{ 99999 | random }}"

    - name: 🏷️ Set final instance name (CLI name if provided, else default)
      set_fact:
        final_instance_name: "{{ instance_name | default(default_instance_prefix ~ '-' ~ suffix) }}"

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ final_instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        tags:
          Name: "{{ instance_name }}"
      register: ec2_result

    - name: Show instance details
      debug:
        msg:
          - "✅ EC2 instance launched successfully:"
          - "  - Instance Name: {{ final_instance_name }}"
          - "  - Instance ID: {{ ec2_result.instance_ids[0] }}"
          - "  - Public IP: {{ ec2_result.instances[0].public_ip_address }}"
