---
- name: Create S3 bucket using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    bucket_name: yaswanth-demo-s3-bucket-{{ 99999 | random }}

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: ap-south-1

    - name: Show created bucket name
      debug:
        msg: "✅ Created bucket name is: {{ bucket_name }}"
